name: CI

on:
    push:
        branches-ignore:
            - "dependabot/**"
    pull_request_target:

jobs:
    lint:
        timeout-minutes: 5
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - name: Linting
              run: |
                  npm i
                  npm run lint
                  npx -y prettier -c .
